# Generated by Django 3.2 on 2023-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igdatabse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default=None, max_length=300, null=True, upload_to='post/')),
            ],
        ),
    ]
